### ISSUE TITLE
TF Log(f), Error(f), Fatal(f), Skip(f), methods add file and line information

### ISSUE THREAD

**Issue by pellared** [goyek/goyek#113]
## Why

Like [testing](https://pkg.go.dev/testing) package it would be very helpful if the "printing" methods add file and line information.

For example, it will help to find where exactly a task is failing.

## How

1. The `TF`'s `Log(f)`, `Error(f)`, `Fatal(f)`, `Skip(f)` add file and line information
2. Add `TF.Helper()` method which works like the one for testing package. 
    > Helper marks the calling function as a test helper function. When printing file and line information, that function will be skipped. Helper may be called simultaneously from multiple goroutines.

Remarks:

1. Printing via `tf.Output()` MUST NOT print file and line information
2. Reference implementation: https://github.com/golang/go/blob/master/src/testing/testing.go

We can consider also adding a field like `Taskflow.DisableCodeline` to provide a possibility to disable such functionality. However, I would rather not add it until someone really needs it. One can always use `tf.Output()` to print without file and line information.

**Comment by pellared** [comment]
@dertseha @sheldonhull WDYT?

**Comment by sheldonhull** [comment]
More context is great!

With go is it possible for me to override the existing log methods? I think I did this before with zerolog and an embedded struct with a pointer to zero log. 

I'm asking because I have some preferred logging output and wasn't sure if I could override an existing function being imported with my own. #newbiegopher 😁

**Comment by pellared** [comment]
@sheldonhull This would require adding some "extensibility point" (e.g. by adding `Logger` field to `Taskflow`). Do you think you will really use it or is it just an idea? Can you share what is your preferred logging output?

**Comment by sheldonhull** [comment]
@pellared no problem. I like using Pterm output as it highlights things making it nice visually to scan through verbose console output. It's not critical. I can still use it independently if needed. Cheers!

**Comment by sheldonhull** [comment]
@pellared  here's an example of why I like pterm. I get that this is not "barebones", but I like that in the middle of all the noise I can use `pterm.Error.Printf()` or `pterm.Success.Printf()` and have a nice bit of color to highlight the progress. 

Is it critical? No.
However, I prefer to provide a nice little bit of polish when I'm using these so often so enjoy this. 

That's why I was asking.
I can still use pterm as I've been doing, just was wondering if there was a way to override imported package methods easily. I did this with zerolog wrapper, but that doesn't seem to fit for goyek.

Not a big deal like I said, just giving some context. 😁 

![2021-07-27-14 13 28-Code](https://user-images.githubusercontent.com/3526320/127214451-988336fc-ac87-4768-9632-716164f1570d.png)

**Comment by pellared** [comment]
@arnovanliere Assigning to you per https://github.com/goyek/goyek/issues/116#issuecomment-1005893313
