### ISSUE TITLE
Access denied in Windows

### ISSUE THREAD

**Issue by obenkenobi** [goyek/goyek#319]
## Description
This may be a problem with how the go runtime works in windows and it possibly having de-elevated permissions but if I try to run the `go build` command on Windows 11 inside my go code, I get an error message like `go: creating work dir: mkdir C:\WINDOWS\go-build1767217485: Access is denied.` 

## Reproduction

In my code I added this following target in goyek
```
import (
	"fmt"
	"github.com/goyek/goyek/v2"
	"github.com/goyek/x/cmd"
	log "github.com/sirupsen/logrus"
	"os"
	"os/exec"
	"path/filepath"
)

var build = goyek.Define(goyek.Task{
	Name:  "build",
	Usage: "build a go binary",
	Deps:  goyek.Deps{wire},
	Action: func(a *goyek.A) {
		path, err := os.Getwd()
		if err != nil {
			log.WithError(err).Fatal()
		}
		executablePath := filepath.Join(path, "bin", "a.out")
		cmd.Exec(a,
			fmt.Sprintf("go build -o %v %v", executablePath, buildPkg()),
			func(a *goyek.A, cmd *exec.Cmd) {
				cmd.Env = []string{"GOOS=" + *osFlag, "GOARCH=" + *archFlag}
			})
	},
})
```
`buildPkg()` just returns my target go package string
`*osFlag` and `*archFlag` are just strings for the GOOS and GOARCH flags

Then just do `go run <path to your goyek main>` -v build

## Expected behavior

The go executable is built succesfully

## Environment

- OS: Windows 11
- Go version: 1.18
- goyek version: v2.0.0-rc.12

**Comment by pellared** [comment]
1. Can you publish minimal code to reproduce the issue? What is the exact expected behavior? Where you want the binary to be build?
2. What is your working directory? What is the `path` returned by `path, err := os.Getwd()`)? Is it `C:\WINDOWS\`? Is it what you want? For sure you need Admin to have write permissions inside `C:\Windows`.
3. Consider debugging `cmd.Exec` - maybe the args are splitted not in the way you wanted. Maybe you should do like so: `fmt.Sprintf("go build -o '%v' '%v'", executablePath, buildPkg()),`.
4. You can use `cmd.Env` instead of `func(a *goyek.A, cmd *exec.Cmd) {
				cmd.Env = []string{"GOOS=" + *osFlag, "GOARCH=" + *archFlag}
			})`

**Comment by pellared** [comment]
@obenkenobi Has anything helped?
